apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gatepulse.fullname" . }}-secret
  labels:
    {{- include "gatepulse.labels" . | nindent 4 -}}
type: Opaque
stringData:
  GP_API_KEY: {{ .Values.auth.apiKey | quote }}
