apiVersion: v1
kind: Service
metadata:
  name: {{ include "gatepulse.fullname" . }}
  labels:
    {{- include "gatepulse.labels" . | nindent 4 -}}�)�����(��������쀹Y��Օ̹͕�٥����������(��������(������������쀹Y��Օ̹͕�٥������Ё��(������хɝ��A���聡���(�������ɽѽ����Q@(����������聡���(��͕���ѽ��(�����촴�����Ց�����ѕ�ձ͔�͕���ѽ�1����̈�����������ЀЀ���(